server:
  ssl:
    enabled: true
    key-alias: configserver
    key-store: src/main/resources/saml/keystore.jks
    key-store-password: '!Ebf4ever'
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: DEBUG

security:
  saml2:
    metadata-url: 'https://dev-552242.okta.com/app/exk1aqrcka9ec9ibd357/sso/saml/metadata'
